# Generated by Django 4.2.7 on 2024-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="librarian",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="library",
            name="books",
            field=models.ManyToManyField(to="relationship_app.book"),
        ),
        migrations.AlterField(
            model_name="library",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
